version: '3'
services:
  nginx:
    build: nginx/
    image: todo/nginx:${GIT_COMMIT_NGINX}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - todo_app
      - backend
      
  node-react:
    build:
      context: frontend/
      args:
        production: "$PRODUCTION"
    image: todo/react:${GIT_COMMIT_REACT}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/todo-app/src:ro
      - ./frontend/build:/app/todo-app/build
    networks:
      - todo_app
      
  node-express:
    build:
      context: backend/
    image: todo/express:${GIT_COMMIT_EXPRESS}
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: mongo:27017
      WAIT_SLEEP_INTERVAL: 2
      WAIT_HOSTS_TIMEOUT: 60
      WAIT_AFTER_HOSTS: 1
    command: sh -c "/wait && npm start"  
    networks:
      - todo_app
      - backend
      
  mongo:
    image: mongo
    volumes:
      - ./backend/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
    restart: always
    hostname: mongo
    command: mongod --noauth
      
networks:
  todo_app:
    driver: bridge
  backend:
    driver: bridge
