version: '3'
services:
  node-react:
    build:
      dockerfile: DockerfileProduction
    environment:
      PRODUCTION: "true"
    image: cesareiv/todo-app:fe-${GIT_COMMIT_REACT}
  
  node-express:
    build:
      dockerfile: DockerfileProduction  
    image: cesareiv/todo-app:be-${GIT_COMMIT_EXPRESS}

  nginx:
    image: cesareiv/todo-app:nginx-${GIT_COMMIT_NGINX}
