version: '3'
services:

  node-express:
    build:
      context: ./
    image: todo/express
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: mongo:27017
    #command: ["./node_modules/mocha/bin/mocha"]
    networks:
      - backend-test
      

  mongo:
    image: mongo
    volumes:
      - ./backend/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend-test
    restart: always
    hostname: mongo
    command: mongod --noauth --smallfiles
      
networks:
  backend-test:
    driver: bridge
