version: '3'
services:

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend-test
    restart: always
    hostname: mongo
    command: mongod --noauth --smallfiles
  
  node-express:
    build:
      context: ./
    image: todo/express:${GIT_COMMIT_EXPRESS}
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: mongo:27017
    networks:
      - backend-test
    command: sh -c "/wait && npm test"
      
networks:
  backend-test:
    driver: bridge
