A# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  docker_build:
    machine: true
    steps:
      - checkout
      - run: docker-compose build
#  backend_api_tests:
#    machine: true      
#    steps:
#      - checkout
#      - run: ./backend/run_backend_tests.sh
workflows:
  version: 2.1
  docker_build_test:
    jobs:
      - flask_docker_build
      - redis_docker_build
      - node_docker_build
      - nginx_docker_build
      - redis_commander_docker_build
#  unit_test:
#    jobs:
#      - backend_api_tests



      
